In [1]:
numbers = [1, 2, 3, 4]
numbers

[1, 2, 3, 4]

In [3]:
import numpy as np

In [4]:
np.__version__

'1.24.3'

In [5]:
numbers = np.array([1, 4, 2, 5, 3])
numbers

array([1, 4, 2, 5, 3])

In [6]:
np.arange(5, 20)  # start, stop


array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [7]:
arr = np.array([1, 4, 2, 5, 3])
arr

array([1, 4, 2, 5, 3])

In [8]:
type(arr)

numpy.ndarray

In [9]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [15]:
numbers_tuple = (1,2,3)
numbers_list = list(numbers_tuple)
numbers

array([1, 4, 2, 5, 3])

In [16]:
type(numbers)

numpy.ndarray

In [17]:
np.array((1,2))

array([1, 2])

In [18]:
np.array([1, 2, 3, 4], dtype='float16')

array([1., 2., 3., 4.], dtype=float16)

In [22]:
np.zeros(17, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [25]:
np.ones((4,8), dtype=float)

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [26]:
np.ones((4,9), dtype=float)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [27]:
np.zeros(7, dtype=float)

array([0., 0., 0., 0., 0., 0., 0.])

In [28]:
np.ones((2,6), dtype=float)

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [29]:
np.full((3,5), 15)

array([[15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15]])

In [30]:
np.full((2,4), 22)

array([[22, 22, 22, 22],
       [22, 22, 22, 22]])

In [31]:
np.full((6,3), 97456)

array([[97456, 97456, 97456],
       [97456, 97456, 97456],
       [97456, 97456, 97456],
       [97456, 97456, 97456],
       [97456, 97456, 97456],
       [97456, 97456, 97456]])

In [33]:
np.zeros(2, dtype=float)

array([0., 0.])

In [34]:
np.zeros(4, dtype=float)

array([0., 0., 0., 0.])

In [35]:
np.ones((2,6), dtype=float)

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [36]:
np.full((2,6), 8)

array([[8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8]])

In [37]:
np.arange
for i in range(0,10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [38]:
np.arange
for malala in range(0,15):
    print(malala)


0
1
2
3
4
5
6
7
8
9
10
11
12
13
14


In [41]:
np.arange
for aina in range(7,17):
    print(aina)

7
8
9
10
11
12
13
14
15
16
