In [196]:
import numpy as np

In [197]:

dataset = np.genfromtxt('../../data/StudentsPerformance.csv', delimiter=',', skip_header=1, dtype=int)
dataset

array([[-1, -1, -1, ..., 72, 72, 74],
       [-1, -1, -1, ..., 69, 90, 88],
       [-1, -1, -1, ..., 90, 95, 93],
       ...,
       [-1, -1, -1, ..., 59, 71, 65],
       [-1, -1, -1, ..., 68, 78, 77],
       [-1, -1, -1, ..., 77, 86, 86]])

In [198]:
print(dataset.ndim)
print(dataset.shape)

2
(1000, 8)


In [199]:
write_scores = dataset[:, -1]
read_scores = dataset[:, -2]
math_scores = dataset[:, -3]

In [200]:
math_scores.shape

(1000,)

## Operaciones aritméticas

Sumatorio de notas

In [201]:
scores = write_scores + read_scores + math_scores
scores[:20]

array([218, 247, 278, 148, 229, 232, 275, 122, 195, 148, 164, 135, 219,
       220, 161, 222, 263,  78, 134, 173])

In [202]:
scores.shape

(1000,)

### Nota Media

In [203]:
final_scores = scores / 3
final_scores = np.round(final_scores, 0)
final_scores[:20]

array([73., 82., 93., 49., 76., 77., 92., 41., 65., 49., 55., 45., 73.,
       73., 54., 74., 88., 26., 45., 58.])

In [204]:
final_scores.dtype

dtype('float64')

In [205]:
final_scores = final_scores.astype(int)
final_scores[:20]

array([73, 82, 93, 49, 76, 77, 92, 41, 65, 49, 55, 45, 73, 73, 54, 74, 88,
       26, 45, 58])

In [206]:
final_scores.dtype

dtype('int32')

## Ordenar

In [207]:
np.sort(final_scores)[-1]

100

In [208]:
final_scores_asc = np.sort(final_scores)
print(f"Nota más baja: {final_scores_asc[0]}")
print(f"Nota más alta: {final_scores_asc[-1]}")

Nota más baja: 9
Nota más alta: 100


## Filtrar datos

In [209]:
success_scores = final_scores[final_scores > 50]
fail_scores = final_scores[final_scores < 50]

In [210]:
print(f"success: {success_scores.shape}")
print(f"fail: {fail_scores.shape}")

success: (883,)
fail: (100,)


In [211]:
fail_index = np.where(final_scores <50)
fail_index

(array([  3,   7,   9,  11,  17,  18,  33,  52,  55,  59,  61,  66,  72,
         74,  75,  76,  80,  81,  84,  91,  93, 131, 136, 143, 145, 174,
        182, 184, 188, 204, 211, 217, 231, 250, 262, 265, 280, 281, 284,
        296, 298, 307, 324, 327, 329, 331, 337, 338, 363, 375, 383, 384,
        395, 401, 424, 448, 455, 466, 527, 528, 552, 554, 555, 564, 565,
        575, 596, 601, 616, 640, 683, 706, 723, 724, 729, 731, 733, 777,
        785, 787, 794, 807, 810, 811, 840, 842, 858, 862, 867, 883, 889,
        895, 896, 902, 910, 921, 928, 978, 980, 988], dtype=int64),)

In [212]:
final_scores[fail_index]

array([49, 41, 49, 45, 26, 45, 40, 46, 39,  9, 37, 40, 47, 46, 41, 26, 49,
       46, 38, 32, 46, 43, 49, 49, 31, 49, 49, 49, 48, 47, 30, 38, 44, 48,
       48, 47, 49, 46, 43, 43, 45, 49, 43, 23, 49, 40, 48, 30, 31, 43, 44,
       41, 45, 46, 38, 45, 47, 32, 44, 39, 46, 46, 35, 48, 45, 49, 23, 29,
       40, 48, 38, 39, 47, 44, 43, 48, 49, 41, 42, 30, 48, 42, 39, 47, 46,
       34, 49, 40, 48, 48, 48, 35, 31, 41, 47, 45, 44, 48, 18, 45])

## Estadísticas

In [213]:
np.mean(final_scores[fail_index])

41.82

In [214]:
np.mean(success_scores)

71.04190260475652

In [215]:
np.mean(final_scores)

67.762

## Mediana

In [216]:
np.median(final_scores)

68.0

In [217]:
np.median(fail_scores)

44.5

In [218]:
np.median(success_scores)

70.0

## Máximo y mínimo

In [219]:
np.max(final_scores)

100

In [220]:
np.max(fail_scores)

49

In [221]:
np.min(success_scores)

51

In [222]:
np.max(success_scores)

100

In [223]:
np.min(fail_scores)

9

In [224]:
np.min(success_scores)

51

In [225]:
np.min(final_scores)

9

In [226]:
np.max(final_scores)

100

## Moda
pip install scipy

https://pypi.org/project/scipy/

In [227]:
from scipy import stats

In [228]:
stats.mode(final_scores, keepdims=False)

ModeResult(mode=68, count=35)

In [229]:
stats.mode(final_scores)

C:\Users\funda\AppData\Local\Temp\ipykernel_10852\219747659.py:1: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  stats.mode(final_scores)


ModeResult(mode=array([68]), count=array([35]))

In [230]:
stats.mode(fail_scores)

C:\Users\funda\AppData\Local\Temp\ipykernel_10852\2801608834.py:1: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  stats.mode(fail_scores)


ModeResult(mode=array([49]), count=array([14]))

In [231]:
stats.mode(success_scores)

C:\Users\funda\AppData\Local\Temp\ipykernel_10852\908123199.py:1: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  stats.mode(success_scores)


ModeResult(mode=array([68]), count=array([35]))

## Desviación estándar-

In [232]:
np.std(final_scores)

14.251222965065137

## Categóricos

Cargar todas las columnas

In [233]:
gender = np.genfromtxt('../../data/StudentsPerformance.csv', delimiter=',', skip_header=1, usecols = (0), dtype=str)
race = np.genfromtxt('../../data/StudentsPerformance.csv', delimiter=',', skip_header=1, usecols = (1), dtype=str)
parent_education = np.genfromtxt('../../data/StudentsPerformance.csv', delimiter=',', skip_header=1, usecols = (2), dtype=str)
lunch = np.genfromtxt('../../data/StudentsPerformance.csv', delimiter=',', skip_header=1, usecols = (3), dtype=str)
preparation = np.genfromtxt('../../data/StudentsPerformance.csv', delimiter=',', skip_header=1, usecols = (4), dtype=str)

## Sacar valores

In [234]:
print(np.unique(gender))
print(np.unique(race))
print(np.unique(parent_education))
print(np.unique(lunch))
print(np.unique(preparation))

['female' 'male']
['group A' 'group B' 'group C' 'group D' 'group E']
["associate's degree" "bachelor's degree" 'high school' "master's degree"
 'some college' 'some high school']
['free/reduced' 'standard']
['completed' 'none']


## Moda

In [235]:
print(stats.mode(gender, keepdims = True))
print(stats.mode(race, keepdims = True))
print(stats.mode(parent_education, keepdims = True))
print(stats.mode(lunch, keepdims = True))
print(stats.mode(preparation, keepdims = True))

ModeResult(mode=array(['female'], dtype='<U6'), count=array([518]))
ModeResult(mode=array(['group C'], dtype='<U7'), count=array([319]))
ModeResult(mode=array(['some college'], dtype='<U18'), count=array([226]))
ModeResult(mode=array(['standard'], dtype='<U12'), count=array([645]))
ModeResult(mode=array(['none'], dtype='<U9'), count=array([642]))


C:\Users\funda\AppData\Local\Temp\ipykernel_10852\3258406433.py:1: DeprecationWarning: Support for non-numeric arrays has been deprecated as of SciPy 1.9.0 and will be removed in 1.11.0. `pandas.DataFrame.mode` can be used instead, see https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.mode.html.
  print(stats.mode(gender, keepdims = True))
C:\Users\funda\AppData\Local\Temp\ipykernel_10852\3258406433.py:2: DeprecationWarning: Support for non-numeric arrays has been deprecated as of SciPy 1.9.0 and will be removed in 1.11.0. `pandas.DataFrame.mode` can be used instead, see https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.mode.html.
  print(stats.mode(race, keepdims = True))
C:\Users\funda\AppData\Local\Temp\ipykernel_10852\3258406433.py:3: DeprecationWarning: Support for non-numeric arrays has been deprecated as of SciPy 1.9.0 and will be removed in 1.11.0. `pandas.DataFrame.mode` can be used instead, see https://pandas.pydata.org/docs/reference/api/pandas.DataFr

## counts

In [236]:
print(np.unique(gender, return_counts=True))
print(type(np.unique(gender, return_counts=True)))


(array(['female', 'male'], dtype='<U6'), array([518, 482], dtype=int64))
<class 'tuple'>


In [237]:
unique, counts = np.unique(gender, return_counts=True)
counts

array([518, 482], dtype=int64)

In [238]:
# zip permite concatenar elemento a elemento de estructuras distintas
dict(zip(unique, counts))

{'female': 518, 'male': 482}

In [239]:
# SELECT COUNT(*) from face
len(race)

1000

In [240]:
import collections

collections.Counter(race)

Counter({'group C': 319,
         'group D': 262,
         'group B': 190,
         'group E': 140,
         'group A': 89})

### Correlación

In [241]:
np.corrcoef(math_scores, read_scores)

array([[1.        , 0.81757966],
       [0.81757966, 1.        ]])

## Cuartiles y Percentiles

In [242]:
print(np.percentile(math_scores, 25))
print(np.percentile(math_scores, 50))
print(np.percentile(math_scores, 75))

57.0
66.0
77.0


In [243]:
print(np.percentile(math_scores, 10))
print(np.percentile(read_scores, 90))

47.0
87.10000000000002


In [244]:
top_10 = math_scores >= np.percentile(math_scores, 90)
math_top_10 = math_scores[top_10]
math_top_10

array([ 90,  88,  88,  97,  88,  98,  87,  99,  91,  88,  87,  89,  87,
        88,  88, 100,  96,  94,  97,  87,  87,  86,  88,  92,  89,  99,
        88,  88,  97,  88,  86,  90,  99,  90,  87,  87,  88,  87,  86,
        89,  86, 100, 100,  91,  90,  94,  95,  86,  91,  97,  92,  87,
        96,  92,  91,  92,  94,  88,  95, 100, 100,  86,  90,  94,  93,
        87,  89,  93,  98,  96,  91,  87,  92,  87,  94,  91,  89,  87,
        90,  87,  94,  90,  91,  87,  97,  87,  97,  90,  93,  86,  88,
        93,  88, 100,  91,  98,  94,  92, 100,  89,  91,  86,  88])

In [245]:
Q1 = np.percentile(math_scores, 25)
Q3 = np.percentile(read_scores, 75)

IQR = Q3 - Q1
IQR

22.0

## Reduce

In [246]:
big_array = np.random.rand(100000000)

In [247]:
%%time
suma = 0
for score in big_array: 
    suma += score
    
print(suma)

50000788.076007284
CPU times: total: 13 s
Wall time: 13.2 s


In [248]:
%%time

np.add.reduce(big_array)

CPU times: total: 172 ms
Wall time: 173 ms


50000788.07599654

## Filtros

In [249]:
data = gender = np.genfromtxt('../../data/StudentsPerformance.csv', delimiter=',',
                              skip_header=1,
                              encoding='utf-8',
                              dtype=None)
data[:10]

array([('female', 'group B', "bachelor's degree", 'standard', 'none', 72, 72, 74),
       ('female', 'group C', 'some college', 'standard', 'completed', 69, 90, 88),
       ('female', 'group B', "master's degree", 'standard', 'none', 90, 95, 93),
       ('male', 'group A', "associate's degree", 'free/reduced', 'none', 47, 57, 44),
       ('male', 'group C', 'some college', 'standard', 'none', 76, 78, 75),
       ('female', 'group B', "associate's degree", 'standard', 'none', 71, 83, 78),
       ('female', 'group B', 'some college', 'standard', 'completed', 88, 95, 92),
       ('male', 'group B', 'some college', 'free/reduced', 'none', 40, 43, 39),
       ('male', 'group D', 'high school', 'free/reduced', 'completed', 64, 64, 67),
       ('female', 'group B', 'high school', 'free/reduced', 'none', 38, 60, 50)],
      dtype=[('f0', '<U6'), ('f1', '<U7'), ('f2', '<U18'), ('f3', '<U12'), ('f4', '<U9'), ('f5', '<i4'), ('f6', '<i4'), ('f7', '<i4')])

In [250]:
print(data.ndim)
print(data.shape)

1
(1000,)


In [251]:
def filter_by_race(data, race_group):
    return data[data[:, 0] == race_group]

In [256]:

filter_by_race(data, 'group c')

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [253]:
indices = np.argsort(math_scores)[:: -1]