In [109]:
import numpy as np

In [110]:
import numpy as np

In [111]:
total_bill = np.genfromtxt('../../data/tips.csv', delimiter=',', skip_header=1,
                           usecols= (0), dtype=float)
total_bill

array([16.99, 10.34, 21.01, 23.68, 24.59, 25.29,  8.77, 26.88, 15.04,
       14.78, 10.27, 35.26, 15.42, 18.43, 14.83, 21.58, 10.33, 16.29,
       16.97, 20.65, 17.92, 20.29, 15.77, 39.42, 19.82, 17.81, 13.37,
       12.69, 21.7 , 19.65,  9.55, 18.35, 15.06, 20.69, 17.78, 24.06,
       16.31, 16.93, 18.69, 31.27, 16.04, 17.46, 13.94,  9.68, 30.4 ,
       18.29, 22.23, 32.4 , 28.55, 18.04, 12.54, 10.29, 34.81,  9.94,
       25.56, 19.49, 38.01, 26.41, 11.24, 48.27, 20.29, 13.81, 11.02,
       18.29, 17.59, 20.08, 16.45,  3.07, 20.23, 15.01, 12.02, 17.07,
       26.86, 25.28, 14.73, 10.51, 17.92, 27.2 , 22.76, 17.29, 19.44,
       16.66, 10.07, 32.68, 15.98, 34.83, 13.03, 18.28, 24.71, 21.16,
       28.97, 22.49,  5.75, 16.32, 22.75, 40.17, 27.28, 12.03, 21.01,
       12.46, 11.35, 15.38, 44.3 , 22.42, 20.92, 15.36, 20.49, 25.21,
       18.24, 14.31, 14.  ,  7.25, 38.07, 23.95, 25.71, 17.31, 29.93,
       10.65, 12.43, 24.08, 11.69, 13.42, 14.26, 15.95, 12.48, 29.8 ,
        8.52, 14.52,

In [112]:
total_bill = np.genfromtxt('../../data/tips.csv', delimiter=',', skip_header=1, usecols= (0), dtype=float)
tip = np.genfromtxt('../../data/tips.csv', delimiter=',', skip_header=1, usecols= (1), dtype=float)
sex = np.genfromtxt('../../data/tips.csv', delimiter=',', skip_header=1, usecols= (2), dtype=str)
smoker = np.genfromtxt('../../data/tips.csv', delimiter=',', skip_header=1, usecols= (3), dtype=str)
day = np.genfromtxt('../../data/tips.csv', delimiter=',', skip_header=1, usecols= (4), dtype=str)
time = np.genfromtxt('../../data/tips.csv', delimiter=',', skip_header=1, usecols= (5), dtype=str)
size = np.genfromtxt('../../data/tips.csv', delimiter=',', skip_header=1, usecols= (6), dtype=int)

In [113]:
print(total_bill[:5])
print(tip[:5])
print(sex[:5])
print(smoker[:5])
print(day[:5])
print(time[:5])
print(size[:5])

[16.99 10.34 21.01 23.68 24.59]
[1.01 1.66 3.5  3.31 3.61]
['"Female"' '"Male"' '"Male"' '"Male"' '"Female"']
['"No"' '"No"' '"No"' '"No"' '"No"']
['"Sun"' '"Sun"' '"Sun"' '"Sun"' '"Sun"']
['"Dinner"' '"Dinner"' '"Dinner"' '"Dinner"' '"Dinner"']
[2 3 3 2 4]


## Categóricas

In [114]:

print(np.unique(sex))
print(np.unique(smoker))
print(np.unique(day))
print(np.unique(time))
print(np.unique(size))

['"Female"' '"Male"']
['"No"' '"Yes"']
['"Fri"' '"Sat"' '"Sun"' '"Thur"']
['"Dinner"' '"Lunch"']
[1 2 3 4 5 6]


In [115]:
import collections



In [116]:
import collections

print(collections.Counter(sex))
print(collections.Counter(smoker))
print(collections.Counter(day))
print(collections.Counter(time))

Counter({'"Male"': 157, '"Female"': 87})
Counter({'"No"': 151, '"Yes"': 93})
Counter({'"Sat"': 87, '"Sun"': 76, '"Thur"': 62, '"Fri"': 19})
Counter({'"Dinner"': 176, '"Lunch"': 68})


In [117]:
# sabado y domingo
filter = np.logical_or(day == "Sat", day == "Sun")
day[filter][:5]

array([], dtype='<U6')

In [118]:
# negando sabado y domingo obtenemos Jueves y viernes
day[(day == "Sat") | (day == "Sun")][:5]

array([], dtype='<U6')

## Numéricas

In [119]:
from scipy import stats

In [120]:
# columna total_bill
print(f"mean: {np.around(np.mean(total_bill), 2)}")
print(f"median: {np.around(np.median (total_bill))}")
print(f"max: {np.max(total_bill)}")
print(f"min: {np.min(total_bill)}")
print(f"std: {np.std(total_bill)}")
print(f"mode: {stats.mode(total_bill, keepdims=True)}")

mean: 19.79
median: 18.0
max: 50.81
min: 3.07
std: 8.884150577771132
mode: ModeResult(mode=array([13.42]), count=array([3]))


In [121]:
# columna tip
print(f"mean: {np.around(np.mean(tip), 2)}")
print(f"median: {np.around(np.median (tip))}")
print(f"max: {np.max(tip)}")
print(f"min: {np.min(tip)}")
print(f"std: {np.std(tip)}")
print(f"mode: {stats.mode(tip, keepdims=True)}")

mean: 3.0
median: 3.0
max: 10.0
min: 1.0
std: 1.3807999538298954
mode: ModeResult(mode=array([2.]), count=array([33]))


In [122]:
# columna size
print(f"mean: {np.around(np.mean(size), 2)}")
print(f"median: {np.around(np.median (size))}")
print(f"max: {np.max(size)}")
print(f"min: {np.min(size)}")
print(f"std: {np.std(size)}")
print(f"mode: {stats.mode(size, keepdims=True)}")

mean: 2.57
median: 2.0
max: 6
min: 1
std: 0.9491488287193913
mode: ModeResult(mode=array([2]), count=array([156]))


In [123]:
len(tip)

244