## bide

In [88]:
import numpy as np
import urllib

In [89]:
# https:archive-beta.ics.uci.edu/dataset/53/iris

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
response = urllib.request.urlopen(url)

data = np.genfromtxt(response, delimiter=",", usecols=(0, 1, 2, 3)) # de golpe todo
data[:10]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [90]:
print(data.ndim)
print(data.shape)

2
(150, 4)


In [91]:
print("Sepal length")
print(f"sepal length mean: {np.mean(data[:, 0]):.2f}")
print(f"sepal length median: {np.median(data[:, 0]):.2f}")
print(f"sepal length max: {np.median(data[:, 0]):.2f}")
print(f"sepal length min: {np.median(data[:, 0]):.2f}")
print(f"sepal length std: {np.std(data[:, 0]):.2f}")

Sepal length
sepal length mean: 5.84
sepal length median: 5.80
sepal length max: 5.80
sepal length min: 5.80
sepal length std: 0.83


In [92]:
# sepal width in cm
print("Sepal width")
print(f"sepal width mean original: {np.mean(data[:, 1]):.2f}")
print(f"sepal width mean rounded: np.{np.mean(data[:, 1]):.2f}")

print(f"sepal width median: {np.mean(data[:, 1]):.2f}")
print(f"sepal width max: {np.max(data[:, 1]):.2f}")
print(f"sepal width min: {np.min(data[:, 1]):.2f}")
print(f"sepal width std: {np.std(data[:, 1]):.2f}")

Sepal width
sepal width mean original: 3.05
sepal width mean rounded: np.3.05
sepal width median: 3.05
sepal width max: 4.40
sepal width min: 2.00
sepal width std: 0.43


In [93]:
# Petal width
print("petal width")
print(f"petal width mean original: {np.mean(data[:, 3]):.2f}")
print(f"petal width mean rounded: np.{np.mean(data[:, 3]):.2f}")

print(f"petal width median: {np.mean(data[:, 3]):.2f}")
print(f"petal width max: {np.max(data[:, 3]):.2f}")
print(f"petal width min: {np.min(data[:, 3]):.2f}")
print(f"petal width std: {np.std(data[:, 3]):.2f}")

petal width
petal width mean original: 1.20
petal width mean rounded: np.1.20
petal width median: 1.20
petal width max: 2.50
petal width min: 0.10
petal width std: 0.76


In [94]:
# Petal length
print("Petal length")
print(f"petal length mean: {np.mean(data[:, 2]):.2f}")
print(f"petal length median: {np.median(data[:, 2]):.2f}")
print(f"petal length max: {np.median(data[:, 2]):.2f}")
print(f"petal length min: {np.median(data[:, 2]):.2f}")
print(f"petal length std: {np.std(data[:, 2]):.2f}")

Petal length
petal length mean: 3.76
petal length median: 4.35
petal length max: 4.35
petal length min: 4.35
petal length std: 1.76


## Busquedas

https://refactoring.guru/refactoring/catalog

In [95]:
# Encontrar el indice de la flor con la longitud del pétalo más larga

PETAL_LENGTH = 2 # position

max_petal_length_index = np.argmax(data[:, PETAL_LENGTH])

max_petal_length_index = data[max_petal_length_index, PETAL_LENGTH]

print("Indice de la longitud del pétalo más larga", max_petal_length_index)
print("longitud del pétalo más larga", max_petal_length_index)

Indice de la longitud del pétalo más larga 6.9
longitud del pétalo más larga 6.9


## ordenar

In [96]:

data[:, 0].argsort() # argsort devuelve índices

array([ 13,  42,  38,   8,  41,  22,   3,   6,  47,   2,  29,  12,  45,
        24,  11,  30,  57, 106,  34,   9,  37,   1,  40,  26,  49,  35,
        43,  60,   7,  93,   4,  25,  44,  46,  98,   0,  39,  17,  23,
        21,  19,  32,  28,  27,  59,  48,  84,   5,  20,  31,  10,  16,
        36,  90,  33,  53,  81,  80,  89,  88, 121,  66,  69,  94,  64,
        79,  96,  99,  15,  55, 113,  18,  95,  67,  14,  92, 114, 142,
        82, 101, 149,  61,  70,  78,  83, 138,  85,  62, 119, 127, 134,
        71,  63,  73,  91,  68,  97, 148, 126,  72, 123, 146,  56, 133,
       100,  87, 136, 103, 132, 128, 137,  51, 115,  74, 111, 104, 116,
       147,  54, 110,  58,  75,  86, 140, 108,  77,  65, 144, 145, 124,
       143,  76, 112, 139, 141,  52, 120,  50, 102, 129, 125, 109, 107,
       130, 105, 122, 118, 117, 135, 131], dtype=int64)

In [97]:
# ordenar po la primera columna ascedentemente
indices = data[:, 0].argsort()[::-1]
data[indices][::-1]

array([[4.3, 3. , 1.1, 0.1],
       [4.4, 3.2, 1.3, 0.2],
       [4.4, 3. , 1.3, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.5, 2.3, 1.3, 0.3],
       [4.6, 3.6, 1. , 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [4.6, 3.4, 1.4, 0.3],
       [4.6, 3.2, 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.8, 3. , 1.4, 0.3],
       [4.8, 3.4, 1.9, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7],
       [4.9, 3.1, 1.5, 0.1],
       [4.9, 3.1, 1.5, 0.1],
       [4.9, 3.1, 1.5, 0.1],
       [4.9, 3. , 1.4, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [5. , 3.4, 1.6, 0.4],
       [5. , 3.3, 1.4, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [5. , 2. , 3.5, 1. ],
       [5. , 3.4, 1.5, 0.2],
       [5. , 2.3, 3.3, 1. ],
       [5. , 3.6, 1.4, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5.1, 3.8, 1.9, 0.4],
       [5.1, 3.8, 1.6, 0.2],
       [5.1, 2

In [102]:
np.sort(data, axis=0)

array([[4.3, 2. , 1. , 0.1],
       [4.4, 2.2, 1.1, 0.1],
       [4.4, 2.2, 1.2, 0.1],
       [4.4, 2.2, 1.2, 0.1],
       [4.5, 2.3, 1.3, 0.1],
       [4.6, 2.3, 1.3, 0.1],
       [4.6, 2.3, 1.3, 0.2],
       [4.6, 2.3, 1.3, 0.2],
       [4.6, 2.4, 1.3, 0.2],
       [4.7, 2.4, 1.3, 0.2],
       [4.7, 2.4, 1.3, 0.2],
       [4.8, 2.5, 1.4, 0.2],
       [4.8, 2.5, 1.4, 0.2],
       [4.8, 2.5, 1.4, 0.2],
       [4.8, 2.5, 1.4, 0.2],
       [4.8, 2.5, 1.4, 0.2],
       [4.9, 2.5, 1.4, 0.2],
       [4.9, 2.5, 1.4, 0.2],
       [4.9, 2.5, 1.4, 0.2],
       [4.9, 2.6, 1.4, 0.2],
       [4.9, 2.6, 1.4, 0.2],
       [4.9, 2.6, 1.4, 0.2],
       [5. , 2.6, 1.4, 0.2],
       [5. , 2.6, 1.5, 0.2],
       [5. , 2.7, 1.5, 0.2],
       [5. , 2.7, 1.5, 0.2],
       [5. , 2.7, 1.5, 0.2],
       [5. , 2.7, 1.5, 0.2],
       [5. , 2.7, 1.5, 0.2],
       [5. , 2.7, 1.5, 0.2],
       [5. , 2.7, 1.5, 0.2],
       [5. , 2.7, 1.5, 0.2],
       [5.1, 2.7, 1.5, 0.2],
       [5.1, 2.8, 1.5, 0.2],
       [5.1, 2

In [98]:
# ordenar por la primera columna descendentemente
# longitudes del sépalo (indice 0)

indices = data[:, 0].argsort() # argsort devuelve índices

data[indices][::-1] # filtra por índices


array([[7.9, 3.8, 6.4, 2. ],
       [7.7, 3. , 6.1, 2.3],
       [7.7, 3.8, 6.7, 2.2],
       [7.7, 2.6, 6.9, 2.3],
       [7.7, 2.8, 6.7, 2. ],
       [7.6, 3. , 6.6, 2.1],
       [7.4, 2.8, 6.1, 1.9],
       [7.3, 2.9, 6.3, 1.8],
       [7.2, 3.6, 6.1, 2.5],
       [7.2, 3.2, 6. , 1.8],
       [7.2, 3. , 5.8, 1.6],
       [7.1, 3. , 5.9, 2.1],
       [7. , 3.2, 4.7, 1.4],
       [6.9, 3.2, 5.7, 2.3],
       [6.9, 3.1, 4.9, 1.5],
       [6.9, 3.1, 5.1, 2.3],
       [6.9, 3.1, 5.4, 2.1],
       [6.8, 3. , 5.5, 2.1],
       [6.8, 2.8, 4.8, 1.4],
       [6.8, 3.2, 5.9, 2.3],
       [6.7, 3.3, 5.7, 2.1],
       [6.7, 3. , 5.2, 2.3],
       [6.7, 3.3, 5.7, 2.5],
       [6.7, 3.1, 4.4, 1.4],
       [6.7, 3. , 5. , 1.7],
       [6.7, 2.5, 5.8, 1.8],
       [6.7, 3.1, 5.6, 2.4],
       [6.7, 3.1, 4.7, 1.5],
       [6.6, 3. , 4.4, 1.4],
       [6.6, 2.9, 4.6, 1.3],
       [6.5, 3.2, 5.1, 2. ],
       [6.5, 2.8, 4.6, 1.5],
       [6.5, 3. , 5.2, 2. ],
       [6.5, 3. , 5.5, 1.8],
       [6.5, 3

In [103]:
indices = data[:, 0].argsort() 

data[indices][0:5, 0:67] 


array([[4.3, 3. , 1.1, 0.1],
       [4.4, 3.2, 1.3, 0.2],
       [4.4, 3. , 1.3, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.5, 2.3, 1.3, 0.3]])

In [100]:
np.sort(data[:, 3], axis=0) # ordena ls columnas

array([0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2,
       0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2,
       0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.3, 0.3, 0.3, 0.3, 0.3,
       0.3, 0.3, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.5, 0.6, 1. , 1. ,
       1. , 1. , 1. , 1. , 1. , 1.1, 1.1, 1.1, 1.2, 1.2, 1.2, 1.2, 1.2,
       1.3, 1.3, 1.3, 1.3, 1.3, 1.3, 1.3, 1.3, 1.3, 1.3, 1.3, 1.3, 1.3,
       1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.5, 1.5, 1.5, 1.5, 1.5,
       1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.6, 1.6, 1.6, 1.6, 1.7, 1.7,
       1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.9,
       1.9, 1.9, 1.9, 1.9, 2. , 2. , 2. , 2. , 2. , 2. , 2.1, 2.1, 2.1,
       2.1, 2.1, 2.1, 2.2, 2.2, 2.2, 2.3, 2.3, 2.3, 2.3, 2.3, 2.3, 2.3,
       2.3, 2.4, 2.4, 2.4, 2.5, 2.5, 2.5])