In [132]:
import numpy as np

In [133]:

names = np.genfromtxt('data/vgsales.csv', usecols=(2), dtype=str,
                      skip_header=1, delimiter=',', invalid_raise=False)
names[:-5]
names.shape

(16598,)

In [134]:

platform = np.genfromtxt('data/vgsales.csv', usecols=(2), dtype=str,
                      skip_header=1, delimiter=',', invalid_raise=False)
platform.shape

(16598,)

In [135]:
year = np.genfromtxt('data/vgsales.csv', usecols=(2), dtype=int,
                      skip_header=1, delimiter=',', invalid_raise=False)
year.shape

(16598,)

In [136]:
genres = np.genfromtxt('data/vgsales.csv', usecols=(2), dtype=str,
                      skip_header=1, delimiter=',', invalid_raise=False)
genres.shape

(16598,)

In [137]:
publishers = np.genfromtxt('data/vgsales.csv', usecols=(2), dtype=str,
                      skip_header=1, delimiter=',', invalid_raise=False)
publishers.shape

(16598,)

In [138]:
# NA_Sales, EU_Sales. JP_Sales, Other_Sales
sales = np.genfromtxt('data/vgsales.csv', usecols=(6, 7, 8, 9), dtype=float,
                      skip_header=1, delimiter=',', invalid_raise=False)
sales.shape

(16598, 4)

In [139]:
np.set_printoptions(suppress=True)
sales

array([[41.49, 29.02,  3.77,  8.46],
       [29.08,  3.58,  6.81,  0.77],
       [15.85, 12.88,  3.79,  3.31],
       ...,
       [ 0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.01,  0.  ,  0.  ],
       [ 0.01,  0.  ,  0.  ,  0.  ]])

In [140]:
# Calcularr ventas totales
np.sum(sales, axis=1).shape

(16598,)

In [141]:
# Calcular ventas totales
total_sales = np.sum(sales, axis=1)
total_sales

array([82.74, 40.24, 35.83, ...,  0.  ,  0.01,  0.01])

In [142]:
# Estadisticas sobre ctotal_sales
total_sales.dtype

dtype('float64')

In [143]:
print(f"{np.mean(total_sales):.2f}")
print(f"{np.median(total_sales)}")
print(f"{np.max(total_sales)}")
print(f"{np.min(total_sales)}")
print(f"{np.std(total_sales):.2f}")

nan
nan
nan
nan
nan


In [144]:
# Detectar si hay nan:
isnan = np.isnan(total_sales)
isnan[isnan == True]

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [145]:
# detectar si hay NaN (missing values o valores faltantes):
# isnan = np.osnan(total_sales)
# isnan[isnan == True]

print(f"Hay NaN: {np.isnan(total_sales).any()}")
print(f"Hay Infinito: {np.isinf(total_sales).any()}")
print(f"Hay Infinito neg: {np.isneginf(total_sales).any()}")


Hay NaN: True
Hay Infinito: False
Hay Infinito neg: False


In [146]:
# Contar cuántos NaN hay
len(total_sales[np.isnan(total_sales)])

123

In [147]:
# Reemplazar por 0 o -1
total_sales2 = np.nan_to_num(total_sales, nan=0)
print(f"{len(total_sales2)}")
print(f"{np.isnan(total_sales2).any()}") # False

16598
False


In [148]:
# Calcular la media de total_sales sin nan: (suma las ventas pero valora los NaN)
total_sales_3 = np.nansum(sales, axis=1)
len(total_sales_3)

16598

In [149]:
# Calcular la media de total_sales sin nan: (suma las ventas pero valora los NaN)
total_sales_3 = np.nansum(sales, axis=1)
np.isnan(total_sales_3).any()

False

In [150]:
# Calcular la media de total_sales sin NaN pero da valor
print(f"{np.nanmean(total_sales)}")

0.5393644916540212


In [151]:
np.isnan(sales).any()


True

In [152]:
np.nan_to_num(sales, nan=0)

array([[41.49, 29.02,  3.77,  8.46],
       [29.08,  3.58,  6.81,  0.77],
       [15.85, 12.88,  3.79,  3.31],
       ...,
       [ 0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.01,  0.  ,  0.  ],
       [ 0.01,  0.  ,  0.  ,  0.  ]])

In [153]:
#Ignorar las filas que tienen NaN
sales_good = sales[~(np.isnan(sales))]
sales_good

array([41.49, 29.02,  3.77, ...,  0.  ,  0.  ,  0.  ])

In [154]:
len(sales_good)

66240

In [155]:
# calcular la media de cada columna ignorando los NaN
mean_per_column = np.nanmean(sales, axis=0)

#crear una máscara boolean de los Nan en el Array
mask = np.isnan(sales)


In [ ]:
total_sales = np.sum

In [160]:
# estadisticas sobre total_sales
print(f"{np.mean(total_sales)}")
print(f"{np.median(total_sales)}")
print(f"{np.max(total_sales)}")
print(f"{np.min(total_sales)}")
print(f"{np.std(total_sales)}")
# sale NaN porque sales tiene elementos NaN, por tanto no se pueden calcular
# estadisticas correctamente


nan
nan
nan
nan
nan


In [188]:
# Identificar los 10 videojuegos más vendidos
total_sales = np.genfromtxt('data/vgsales.csv', usecols=(9), dtype=float,
                      skip_header=1, delimiter=',', invalid_raise=False)
indices = np.argsort(total_sales)[::-1]
names[indices][:10]

array(['PS2', 'Wii', 'PS2', 'PS3', 'Wii', 'Wii', 'PS2', 'DS', 'Wii', 'DS'],
      dtype='<U48')

In [184]:
np.isnan(total_sales).any()

False

In [201]:
# Calcular ventas totales por plataforma
unique_platform = np.unique(platform)
unique_platform

array([' A-Kata', ' Badman! What Did I Do to Deserve This?"',
       ' Be Glorious!"', ' Be Gracious!"', ' Boku to Himitsu no Chizu"',
       ' Camera', ' Diego', ' Dood!"', ' Edd n Eddy: Jawbreakers!"',
       ' Edd n Eddy: The Mis-Edventures"', ' Fashion and Friends"',
       ' Futatabi"', ' Ginkaku no Inbou"', ' Hajime Mashita"',
       ' Hidden Dragon"', ' Himawari no Shoujo"', ' Inc. Scream Arena"',
       ' Inc. Scream Team"', ' Inc."', ' Inc.: Mega MicroGame$"',
       ' Inc.: Mega Party Game$"', ' Kai-lan: New Year\'s Celebration"',
       ' Kai-lan: Super Game Day"', ' Keiyaku Shikkou Dechai masuu"',
       ' Kimi ni"', ' Koi Utsutsu: Setsugetsuka Koi Emaki"',
       ' Koiseyo Otome! Love is Power!!!"',
       ' Kono Sekai ni Kami-sama ga Iru to suru Naraba."',
       ' Kore ga Otoko Dearu!"', ' London 1969"', ' Mahjong & Tangram"',
       ' Mon Meilleur Ami"', ' Monkey Do!"', ' My Friend',
       ' My Lord!? 2"', ' My Love"', ' My Way (US sales)"',
       ' Myths & Legends"',

In [203]:
genres = np.genfromtxt('data/vgsales.csv', usecols=(2), dtype=str,
                      skip_header=1, delimiter=';',encoding="uft-8")
genres = np.unique(genres)

LookupError: unknown encoding: uft-8